import pandas as pd
import numpy as np
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt


# A designated split allways increases the relationship between the variable "X" and "Y".
# Both "X" and "Y" have values in [0,1].
# The split can take place in “X” and “Y” as well as in a third or fourth variable “Kn” or “Kt”.
# "Kn” is a continuous variable with values in [0,1].
# "Kt" is a categorical variable with attributes {"A", "B", "C", "D", "E"}.


seed_val = None
# To generate pseudo-random, reproducible results.
# The following function is used to increase the local seed value by 1 ...
# ... after each application of a random realization ...
# ... so that all realizations/variables are different:
def SEED():
    global seed_val
    np.random.seed(seed_val)
    seed_val = seed_val + 1 if seed_val is not None else seed_val



depth_faktor = 2/3
type_list = ["lin", "squ", "cub", "exp", "srt", "sin", "ggk"]


# Automated plot of the data set using seaborn pairplot:
def print_dataset(df):
    sns.pairplot(df, diag_kind="kde", plot_kws=dict(marker="x", alpha = 0.9, linewidth=0.08))
    plt.show()


#____________________________________________________________
#____________________________________________________________
# Fundamental function to automatically create data sets with a relationship between the variables “X” and “Y”,
  # - which have an arbitrarily adjustable strength
  # - and whose type of relationship can be varied (see type_list):


def create_dataset(r_S, size=1000, xlim_min = 0, xlim_max =1, depth = 1, type ="lin"):
    # Slope and translation term are determined by...
    #   - the interval limits of the X- and Y-variables     (xlim_max - xlim_min), (ylim_max - ylim_min),
    #   - the strength of the relationship,                 (r_S)
    #   - and the combination with a depth factor.          (depth)
    # (see Table 3.4).
    m = r_S * 0.6 * ((depth_faktor) ** (depth - 1))
    n = 0.5-0.5*m
    x1 = np.arange(1, size + 1)
    alpha = 0.001                            # Conditions for significance testing of the correlation ...
    p_value, corr, exit_p = 1, -999, 0       # ... and termination criterion for the while loop.

    while True:
        exit_p = exit_p + 1

        # Relationship with the strength r_S between the variables x1 and x2 ...
        # ... using an independent variable (see subsection 3.3.2):
        SEED(); x2_independent = np.random.normal(0, 1, size)
        x2 = (r_S * (x1 - np.mean(x1)) / np.std(x1) + np.sqrt(1 - r_S ** 2) * x2_independent)

        a, b = np.polyfit(x1, x2, 1)   # Identify the regression line x2 = a*x1+b
        x2 = ((x2 - b) / a) / size          # Normalize to x2 = 1*x1 + 0
        x2 = x2 *m*(xlim_max-xlim_min)      # Adjusting the slope factor to the desired shape
        x2 = x2 + n + m*xlim_min            # Translate the values of the x2-axis to the desired shape
        for i in range(len(x2)):            # Redistribution of all x2 values outside [0, 1]:
            if (x2[i] <= 0) or (x2[i] >1):
                SEED(); x2[i] = np.random.randint(1, 10001) / 10000

        corr, p_value = stats.pearsonr(x1, x2)
        # Checks the strength and significance of the correlation.
        if (p_value <= alpha) & (abs(corr - r_S) < 0.01):
            break
        # Termination criterion if no result is achieved.
        if exit_p >= 1000:
            print("Requirements not satisfied")
            return

    # The monotonic relationships are generated by composition terms that are applied to the linear case
    # (see Table 3.4)
    if type == "lin":
        x2 = x2
        x1 = (x1 * (xlim_max - xlim_min) / size) + xlim_min
    elif type == "squ":     #
        x2 = x2**2
        x1 = (x1 * (xlim_max - xlim_min) / size) + xlim_min
    elif type == "cub":
        x2 = x2**3
        x1 = (x1 * (xlim_max - xlim_min) / size) + xlim_min
    elif type == "exp":
        x2 = (10**x2) / 10
        x1 = (x1 * (xlim_max - xlim_min) / size) + xlim_min
    elif type == "srt":
        x2 = np.sqrt(x2)
        x1 = (x1 * (xlim_max - xlim_min) / size) + xlim_min

    # The non-monotonic correlations arise, analogous to the linear case, directly from the regression curve
    # (see Table 3.4)
    elif type == "sin":
        x1 = (x1 * (xlim_max - xlim_min) / size) + xlim_min
        x2_mean = m/2*np.sin(3 * np.pi * (x1)) + 0.5
        x2 = (r_S * (x2_mean - np.mean(x2_mean)) / np.std(x2_mean)
              + np.sqrt(1 - r_S ** 2) * x2_independent)
        x2 = x2 * np.std(x2_mean) + np.mean(x2_mean)
        for i in range(len(x2)):
            if (x2[i] <= 0) or (x2[i] >1):
                SEED(); x2[i] = np.random.randint(1, 10001) / 10000
    elif type == "ggk":
        x1 = (x1*(xlim_max - xlim_min)/size) + xlim_min
        mu, sigma = 0.5, 0.1  # Default values for mean value and standard deviation
        x2_mean = m * np.exp(-((x1 - mu) ** 2) / (2 * sigma ** 2)) + (0.5 - 0.5 * m)
        x2 = (r_S * (x2_mean - np.mean(x2_mean)) / np.std(x2_mean)
              + np.sqrt(1 - r_S ** 2) * x2_independent)
        x2 = x2 * np.std(x2_mean) + np.mean(x2_mean)
        for i in range(len(x2)):
            if (x2[i] <= 0) or (x2[i] > 1):
                SEED(); x2[i] = np.random.randint(1, 10001) / 10000

    else:
        print(f"Type '{type}' does not exist.")
        exit()

    # Create a panda-df from the variables x1 and x2
    df = pd.DataFrame({'X': x1, 'Y':x2})
    return df

# First, the functions that can be used to create specific types of datasets are explained.
# At the end of the file, a higher-level function combines these individual dataset types.
#____________________________________________________________
#____________________________________________________________
# At the beginning, the data sets that only have a designated division are generated.
# For reasons of clarity (especially for the later process), ...
# ... a separate function is defined for each data set:


def create_X(r_S, printit = False, type ="lin"):
    df = create_dataset(r_S= r_S, type = type)                  # Partial data set with existing relationship
    df["X"] = df["X"]/10                                        # Applying the threshold value (X ≤ 0.1)
    SEED(); x1_rand = np.random.randint(1001,10001, 9000)/10000 # Generating the remaining data set
    SEED(); x2_rand = np.random.randint(1,10001, 9000)/10000
    df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand})      # Combine both partial data sets
    df = pd.concat([df, df_append], ignore_index= True)
    if printit: print_dataset(df)
    return df

#create_X(.99, printit = True, type = "lin")

def create_Kn(r_S, printit = False, type ="lin"):
    df = create_dataset(r_S=r_S, type = type)                              # Partial data set with existing relationship
    SEED(); x3_df = np.random.randint(1,1001, 1000)/10000                  # Applying the threshold value (Kn ≤ 0.1)
    df["Kn"] =x3_df
    SEED(); x1_rand = np.random.randint(1,10001, 9000)/10000               # Generating the remaining data set
    SEED(); x2_rand = np.random.randint(1,10001, 9000)/10000
    SEED(); x3_rand = np.random.randint(1001,10001, 9000)/10000
    df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, "Kn": x3_rand})  # Combine both partial data sets
    df = pd.concat([df, df_append], ignore_index=True)
    if printit: print_dataset(df)
    return df

#df = create_Kn(0.99999, printit = True, type = "ggk")

def create_Kt(r_S, printit = False, type ="lin"):
    df = create_dataset(r_S=r_S, type = type)                              # Partial data set with existing relationship
    x3_df =  ["A"] * 1000                                                  # Applying the relevant class (Kt = "A")
    df["Kt"] = x3_df
    SEED(); x1_rand = np.random.randint(1,10001, 9000)/10000               # Generating the remaining data set
    SEED(); x2_rand = np.random.randint(1,10001, 9000)/10000
    SEED(); x3_rand = np.random.choice(["B", "C", "D", "E"], 9000)
    df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, "Kt": x3_rand})  # Combine both partial data sets
    df = pd.concat([df, df_append], ignore_index=True)
    if printit: print_dataset(df)
    return df

#df = create_Kt(0.999, printit = True, type = "lin")

def create_Y(r_S, printit = False, type = "linear"):
    df = create_dataset(r_S=r_S, type = type)                 # Partial data set with existing relationship
    X = df["Y"]                                                     # Interchange X- and Y-coordinates
    Y  = df["X"] / 10                                               # Applying the relevant class (Y ≤ 0.1)
    df = pd.DataFrame({'X': X, 'Y': Y})
    SEED(); x1_rand = np.random.randint(1,10001, 9000)/10000        # Generating the remaining data set
    SEED(); x2_rand = np.random.randint(1001,10001, 9000)/10000
    df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand})          # Combine both partial data sets
    df = pd.concat([df, df_append], ignore_index= True)
    if printit: print_dataset(df)
    return df

#df = create_Y(1, printit = True, type = "lin")


#____________________________________________________________
#____________________________________________________________
# Secondly, the data sets that already have two designated splits are generated.
# Since the relationship between X and Y in the partial data set after two splits should follow...
#    ... the same, modified regression curve as the one from the partial data set after one split, ...
#    ... the previously defined functions would be difficult to implement. Therefore, each of ...
#    ... the following functions constructs the high-functional relationship already according to the ...
#    ... regression curve of the partial data set with the weakest relationship (see subsection 3.3.1).
# As the creation is done “from the back to the front”, the second split is already defined...
#    ... for a particular function, while the first split is variable:


def create_var1_X(r_S, var1, printit = False, type = "lin"):
    # Create the highly functional relationship after two split (df_sign) ...
    # ... and the weakened relationship after one split (df_rest) and combine both.
    # The second split is implemented at the threshold value X ≤ 0.1:
    df_sign = create_dataset(r_S=r_S, size=1000, xlim_min = 0, xlim_max = 0.1, depth = 2, type = type)
    df_rest = create_dataset(r_S=r_S * depth_faktor, size=9000, xlim_min = 0.1, xlim_max = 1, depth = 1, type = type)
    df = pd.concat([df_sign, df_rest], ignore_index=True)

    # Depending on the first split the previously generated data set is adjusted ...
    # ... and the remaining partial data set is created:

    if var1 == "Kn":            # First Split: Kn, Second Split: X
        SEED(); x3 = np.random.randint(1,5001, 10000)/10000 # The first split is set at the threshold value (Kn ≤ 0.5)
        df["Kn"] = x3
        SEED(); x1_rand = np.random.randint(1,    10001, 10000)/10000
        SEED(); x2_rand = np.random.randint(1,    10001, 10000)/10000
        SEED(); x3_rand = np.random.randint(5001, 10001, 10000)/10000
        df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kn': x3_rand})

    elif var1 == "Kt":          # First Split: Kt, Second Split: X
        x3 =  ["B"] * 10000     # The first split is set at the relevant class (Kt = "B")
        df["Kt"] = x3
        SEED(); x1_rand = np.random.randint(1, 10001, 10000) / 10000
        SEED(); x2_rand = np.random.randint(1, 10001, 10000) / 10000
        SEED(); x3_rand = np.random.choice(["A", "C", "D", "E"], 10000)
        df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kt': x3_rand})

    elif var1 == "Y":           # First Split: Y, Second Split: X
        df["Y"] = df["Y"]/2     # The first split is set at the threshold value (Y ≤ 0.5)
        SEED(); x1_rand = np.random.randint(1,   10001, 10000)/10000
        SEED(); x2_rand = np.random.randint(5001,10001, 10000)/10000
        df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand})

    df = pd.concat([df, df_append], ignore_index=True)   # Both partial data sets are merged and returned
    if printit: print_dataset(df)
    return df

#create_var1_X(1, "Kn", printit = True, type = "lin")
#create_var1_X(1, "Kt", printit = True, type = "lin")
#create_var1_X(0.8, "Y", printit = True, type = "lin")

def create_var1_Kn(r_S, var1, printit = False, type ="lin"):
    # Create the highly functional relationship after two split (df) ...
    # ... and the weakened relationship after one split (df_append) and combine both.
    # The second split is implemented at the threshold value Kn ≤ 0.1:
    df = create_dataset(r_S=r_S, size = 1000, depth = 2, type = type)
    SEED(); x3_df = np.random.randint(1,1001, 1000)/10000
    df["Kn"] =x3_df
    df_append = create_dataset(r_S=r_S * depth_faktor, size = 9000, depth = 1, type = type)
    SEED(); x3_append = np.random.randint(1001, 10001, 9000)/10000
    df_append["Kn"] =x3_append
    df = pd.concat([df, df_append], ignore_index=True)

    # Depending on the first split the previously generated data set is adjusted ...
    # ... and the remaining partial data set is created:

    if var1 == "X":         # First Split: X, Second Split: Kn
        df["X"] /=2         # The first split is set at the threshold value (X ≤ 0.5)
        SEED(); x1_rand = np.random.randint(5001,10001, 10000) / 10000
        SEED(); x2_rand = np.random.randint(1,   10001, 10000) / 10000
        SEED(); x3_rand = np.random.randint(1,   10001, 10000) / 10000
        df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kn': x3_rand})

    elif var1 == "Kt":      # First Split: Kt, Second Split: Kn
        x4 = ["B"] * 10000  # The first split is set along the relevant class (Kt = "B")
        df["Kt"] = x4
        SEED(); x1_rand = np.random.randint(1,10001, 10000) / 10000
        SEED(); x2_rand = np.random.randint(1,10001, 10000) / 10000
        SEED(); x3_rand = np.random.randint(1,10001, 10000) / 10000
        SEED(); x4_rand = np.random.choice(["A", "C", "D", "E"], 10000)
        df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kn': x3_rand, 'Kt': x4_rand})

    elif var1 == "Y":       # First Split: Y, Second Split: Kn
        df["Y"] /= 2        # The first split is set at the threshold value(Y ≤ 0.5)
        SEED(); x1_rand = np.random.randint(1,   10001, 10000) / 10000
        SEED(); x2_rand = np.random.randint(5001,10001, 10000) / 10000
        SEED(); x3_rand = np.random.randint(1,   10001, 10000) / 10000
        df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kn': x3_rand})

    df = pd.concat([df, df_append], ignore_index=True) # Both partial data sets are merged and returned
    if printit: print_dataset(df)
    return df

#create_var1_Kn(1,"X", printit = True, type = "lin")
#create_var1_Kn(1,"Kt", printit = True, type = "lin")
#create_var1_Kn(1,"Y", printit = True, type = "lin")

def create_var1_Kt(r_S, var1, printit = False, type ="lin"):
    # Create the highly functional relationship after two split (df) ...
    # ... and the weakened relationship after one split (df_append) and combine both.
    # The second split is implemented along the relevant class Kt = "A":
    df = create_dataset(r_S=r_S, size = 1000, depth = 2, type = type)
    x3 = ["A"] * 1000
    df['Kt'] = x3
    df_append = create_dataset(r_S=r_S * depth_faktor, size = 9000, depth = 1, type = type)
    SEED(); x3_append = np.random.choice(["B", "C", "D", "E"], 9000)
    df_append['Kt'] = x3_append
    df = pd.concat([df, df_append], ignore_index=True)

    # Depending on the first split the previously generated data set is adjusted ...
    # ... and the remaining partial data set is created:

    if var1 == "X":         # First Split: X, Second Split: Kt
        df['X'] /= 2        # The first split is set at the threshold value (X ≤ 0.5)
        SEED(); x1_rand = np.random.randint(5001,10001, 10000) / 10000
        SEED(); x2_rand = np.random.randint(1,   10001, 10000) / 10000
        SEED(); x3_rand = np.random.choice(["A", "B", "C", "D", "E"], 10000)
        df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kt': x3_rand})

    if var1 == "Kn":            # First Split: Kn, Second Split: Kt
        SEED(); x4_append = np.random.randint(1,    5001, 10000) / 10000
        df['Kn'] = x4_append    # The first split is set at the threshold value (Kn ≤ 0.5)
        SEED(); x1_rand = np.random.randint(1,   10001, 10000) / 10000
        SEED(); x2_rand = np.random.randint(1,   10001, 10000) / 10000
        SEED(); x3_rand = np.random.choice(["A", "B", "C", "D", "E"], 10000)
        SEED(); x4_rand = np.random.randint(5001,10001, 10000) / 10000
        df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kt': x3_rand, 'Kn':x4_rand})

    if var1 == "Y":         # First Split: Y, Second Split: Kt
        df['Y'] /= 2        # The first split is set at the treshold value (Y ≤ 0.5)
        SEED(); x1_rand = np.random.randint(1,   10001, 10000) / 10000
        SEED(); x2_rand = np.random.randint(5001,10001, 10000) / 10000
        SEED(); x3_rand = np.random.choice(["A", "B", "C", "D", "E"], 10000)
        df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kt': x3_rand})

    df = pd.concat([df, df_append], ignore_index=True) # Both partial data sets are merged and returned
    if printit: print_dataset(df)
    return df

#create_var1_Kt(.1,"X",True, type = "lin")
#create_var1_Kt(.5,"Kn",True, type = "lin")
#create_var1_Kt(1,"Y",True, type = "lin")

def create_var1_Y(r_S, var1, printit = False, type ="lin"):
    # Create the highly functional relationship after two split (df) ...
    # ... and the weakened relationship after one split (df_append) and combine both.
    # The second split is implemented along the threshold value Y ≤ 0.1:
    # To simplify the construction, the case with a last split in Y can be traced back ...
    # ... to the case with the last split in X by interchanging the indices
    df = create_dataset(r_S=r_S, size = 1000, xlim_min = 0, xlim_max = 0.1, depth = 2, type = type)
    X, Y = df["Y"], df["X"]     # Interchange X- and Y-Coordinates
    df["X"], df["Y"] = X, Y
    df_append = create_dataset(r_S=r_S * depth_faktor, size = 9000, xlim_min = 0.1, xlim_max = 1, depth = 1, type = type)
    X, Y = df_append["Y"], df_append["X"]
    df_append["X"], df_append["Y"] = X, Y
    df = pd.concat([df, df_append], ignore_index= True)

    # Depending on the first split the previously generated data set is adjusted ...
    # ... and the remaining partial data set is created:

    if var1 == "X":                 # First Split: X, Second Split: Y
        df["X"] /= 2                # The first split is set at the threshold value (X ≤ 0.5)
        SEED(); x1_rand = np.random.randint(5001,10001, 10000) / 10000
        SEED(); x2_rand = np.random.randint(1   ,10001, 10000) / 10000
        df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand})

    if var1 == "Kn":                # First Split: Kn, Second Split: Y
        SEED(); x3_append = np.random.randint(1,5001, 10000) / 10000
        df["Kn"] = x3_append        # The first split is set at the threshold value (Kn ≤ 0.5)
        SEED(); x1_rand = np.random.randint(1,   10001, 10000) / 10000
        SEED(); x2_rand = np.random.randint(1,   10001, 10000) / 10000
        SEED(); x3_rand = np.random.randint(5001,10001, 10000) / 10000
        df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kn':x3_rand})

    if var1 == "Kt":                # First Split: Kt, Second Split: Y
        x3_append = ["B"] * 10000   # The first split is set along the relevant class (Kt = "B")
        df['Kt'] = x3_append
        SEED(); x1_rand = np.random.randint(1,   10001, 10000) / 10000
        SEED(); x2_rand = np.random.randint(1,   10001, 10000) / 10000
        SEED(); x3_rand = np.random.choice(["A", "C", "D", "E"], 10000)
        df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kt':x3_rand})

    df = pd.concat([df, df_append], ignore_index= True) # Both partial data sets are merged and returned
    if printit: print_dataset(df)
    return df

#create_var1_Y(1, "X", printit = True, type = "lin")
#create_var1_Y(1, "Kn", printit = True, type = "lin")
#create_var1_Y(1, "Kt", printit = True, type = "lin")

#____________________________________________________________
#____________________________________________________________
# Thirdly, the data sets that have three designated splits are generated.
# With the same reasoning as for data sets with two splits (see subsection 3.3.1), ...
# ... the data sets for three splits are also created from back to front, ...
# ... whereby the form of the regression curve of the weakest relationship (after 1 split) ...
# ... is already taken into account for the construction of the (first) highest functional relationship (after 3 splits).


def create_var1_var2_X(r_S, var1, var2, printit = False, type ="lin"):
    # Create the highly functional relationship after three splits (df_sign) ...
    # ... and a weakened relationship after two splits (df_rest) and combine both.
    # The third split is implemented along the threshold value X ≤ 0.1:
    df_sign = create_dataset(r_S=r_S, size=1000, xlim_min = 0, xlim_max = 0.1, depth = 3, type = type)
    df_rest = create_dataset(r_S=r_S * depth_faktor, size=9000, xlim_min = 0.1, xlim_max = 1, depth = 2, type = type)
    df = pd.concat([df_sign, df_rest], ignore_index=True)

    # Depending on the first and second split the previously generated data set is adjusted ...
    # ... and the remaining partial data sets are created:


    if var2 == "Kt":            # Second Split: Kt, Third Split: X
        x3 =  ["B"] * 10000     # The second Split is set along the relevant class (Kt = "B")
        df["Kt"] = x3
        df_append = create_dataset(r_S=r_S * (depth_faktor ** 2), size=10000,
                                   xlim_min = 0, xlim_max = 1, depth = 1, type = type)
        SEED(); x3_append = np.random.choice(["A", "C", "D", "E"], 10000)
        df_append['Kt'] = x3_append
        df = pd.concat([df, df_append], ignore_index=True)

        if var1 == "Kn":                    # First Split: Kn, Second Split: Kt, Third Split: X
            SEED(); x4 = np.random.randint(1,   5001, 20000) / 10000
            df['Kn'] = x4                   # The first Split is set at the threshold value (Kn ≤ 0.5)
            SEED(); x1_rand = np.random.randint(1,    10001, 20000) / 10000
            SEED(); x2_rand = np.random.randint(1,    10001, 20000) / 10000
            SEED(); x3_rand = np.random.choice(["A", "B", "C", "D", "E"], 20000)
            SEED(); x4_rand = np.random.randint(5001, 10001, 20000) / 10000
            df_append = pd.DataFrame({'X':x1_rand, 'Y': x2_rand, 'Kt': x3_rand, 'Kn': x4_rand})

        elif var1 == "Y":                   # First Split: Y, Second Split: Kt, Third Split: X
            df["Y"] /= 2                    # The first Split is set at the threshold value (Y ≤ 0.5)
            SEED(); x1_rand = np.random.randint(1,   10001, 20000) / 10000
            SEED(); x2_rand = np.random.randint(5001,10001, 20000) / 10000
            SEED(); x3_rand = np.random.choice(["A", "B", "C", "D", "E"], 20000)
            df_append = pd.DataFrame({'X':x1_rand, 'Y': x2_rand, 'Kt': x3_rand})


    elif var2 == "Kn":      # Second Split: Kn, Third Split: X
        SEED(); x3 = np.random.randint(1,5001, 10000)/10000
        df["Kn"] = x3       # The second Split is set at the threshold value (Kn ≤ 0.5)
        df_append = create_dataset(r_S=r_S * (depth_faktor ** 2), size=10000,
                                   xlim_min = 0, xlim_max = 1, depth = 1, type = type)
        SEED(); x3_append = np.random.randint(5001, 10001, 10000)/10000
        df_append['Kn'] = x3_append
        df = pd.concat([df, df_append], ignore_index=True)

        if var1 == "Kt":                    # First Split: Kt, Second Split: Kn, Third Split: X
            x4 = ["C"]*20000                # The first Split is set along the relevant class (Kt = "C")
            df['Kt'] = x4
            SEED(); x1_rand = np.random.randint(1,10001, 20000)/10000
            SEED(); x2_rand = np.random.randint(1,10001, 20000)/10000
            SEED(); x3_rand = np.random.randint(1,10001, 20000)/10000
            SEED(); x4_rand = np.random.choice(["A", "B", "D", "E"], 20000)
            df_append = pd.DataFrame({'X':x1_rand, 'Y': x2_rand, 'Kn': x3_rand, 'Kt': x4_rand})

        elif var1 == "Y":                   # First Split: Y, Second Split: Kn, Third Split: X
            df["Y"] /= 2                    # The first Split is set at the threshold value (Y ≤ 0.5)
            SEED(); x1_rand = np.random.randint(1,   10001, 20000)/10000
            SEED(); x2_rand = np.random.randint(5001,10001, 20000)/10000
            SEED(); x3_rand = np.random.randint(1,   10001, 20000)/10000
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kn': x3_rand})


    elif var2 == "Y":           # Second Split: Y, Third Split: X
        df["Y"]  = df["Y"]/2    # The second Split is set at the threshold value (Y ≤ 0.5)
        df_append = create_dataset(r_S=r_S * (depth_faktor ** 2), size=10000,
                                   xlim_min = 0, xlim_max = 1, depth = 1, type = type)
        df_append['Y'] = df_append['Y']/2 + 0.5
        df = pd.concat([df, df_append], ignore_index=True)

        if var1 == "Kn":                    # First Split: Kn, Second Split: Y, Third Split: X
            SEED(); x3 = np.random.randint(1,5001, 20000) / 10000
            df['Kn'] = x3                   # The first Split is set at the threshold value (Kn ≤ 0.5)
            SEED(); x1_rand = np.random.randint(1,   10001, 20000)/10000
            SEED(); x2_rand = np.random.randint(1,   10001, 20000)/10000
            SEED(); x3_rand = np.random.randint(5001,10001, 20000)/10000
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kn': x3_rand})

        if var1 == "Kt":                    # First Split: Kt, Second Split: Y, Third Split: X
            x3 = ["C"] * 20000              # The first Split is set along the relevant class (Kt = "C")
            df['Kt'] = x3
            SEED(); x1_rand = np.random.randint(1,   10001, 20000)/10000
            SEED(); x2_rand = np.random.randint(1,   10001, 20000)/10000
            SEED(); x3_rand = np.random.choice(["A", "B", "D", "E"], 20000)
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kt': x3_rand})

    df = pd.concat([df, df_append], ignore_index=True)   # The partial data sets are merged and returned
    if printit: print_dataset(df)
    return df

#create_var1_var2_X(1,"Kn", "Kt", printit = True, type = "lin")
#create_var1_var2_X(1,"Y",  "Kt", printit = True, type = "lin")
#create_var1_var2_X(1,"Kt", "Kn", printit = True, type = "lin")
#create_var1_var2_X(1,"Y",  "Kn", printit = True, type = "lin")
#create_var1_var2_X(1,"Kn", "Y", printit = True, type = "lin")  # NOTE: this case is excluded in the thesis.
#create_var1_var2_X(1,"Kt", "Y", printit = True, type = "lin")  # NOTE: this case is excluded in the thesis.
                                                                # The two data sets that can be called up here only...
                                                                # ... serve to illustrate the problem that arises.

def create_var1_var2_Kn(r_S, var1, var2, printit = False, type ="lin"):
    # Create the highly functional relationship after three splits (df) ...
    # ... and a weakened relationship after two splits (df_append) and combine both.
    # The third split is implemented along the threshold value Kn ≤ 0.1:
    df = create_dataset(r_S=r_S, size = 1000, depth = 3, type = type)
    SEED(); x3_df = np.random.randint(1,1001, 1000)/10000
    df["Kn"] =x3_df
    df_append = create_dataset(r_S=r_S * depth_faktor, size = 9000, depth = 2, type = type)
    SEED(); x3_append = np.random.randint(1001, 10001, 9000)/10000
    df_append["Kn"] =x3_append
    df = pd.concat([df, df_append], ignore_index=True)

    # Depending on the first and second split the previously generated data set is adjusted ...
    # ... and the remaining partial data sets are created:

    if var2 == "X": # NOTE: A new initial data set is created here to adjust the limits ...
                    # ... for the X-Split to the gradient of the subsequent Kn-Split.
        df = create_dataset(r_S=r_S, size=1000, depth=3, xlim_min = 0, xlim_max = 0.5, type = type)
        SEED(); x3_df = np.random.randint(1, 1001, 1000) / 10000
        df["Kn"] = x3_df
        df_append = create_dataset(r_S=r_S * depth_faktor, size=9000, depth=2, xlim_min = 0,
                                   xlim_max = 0.5, type = type)
        SEED(); x3_append = np.random.randint(1001, 10001, 9000) / 10000
        df_append["Kn"] = x3_append
        df = pd.concat([df, df_append], ignore_index=True)

        # Data set for the second split:
        # Second Split: X, Third Split: Kn
        # The second split is set at the threshold value (X ≤ 0.5)
        df_append = create_dataset(r_S=r_S * (depth_faktor ** 2), size=10000,
                                   xlim_min = 0.5, xlim_max = 1, depth = 1, type = type)
        SEED(); x3_rand = np.random.randint(1,   10001, 10000) / 10000
        df_append["Kn"] = x3_rand
        df = pd.concat([df, df_append], ignore_index=True)

        if var1 == "Kt":                        # First Split: Kt, Second Split: X, Third Split: Kn
            df["Kt"] =  ["C"] * 20000           # The first split is set along the relevant class (Kt = "C")
            SEED(); x1_rand = np.random.randint(1,   10001, 20000)/10000
            SEED(); x2_rand = np.random.randint(1,   10001, 20000)/10000
            SEED(); x3_rand = np.random.randint(1,   10001, 20000)/10000
            SEED(); x4_rand = np.random.choice(["A", "B", "D", "E"], 20000)
            df_append = pd.DataFrame({'X':x1_rand, 'Y':x2_rand, 'Kn': x3_rand, 'Kt':x4_rand})

        if var1 == "Y":                         # First Split: Y, Second Split: X, Third Split: Kn
            df["Y"] /= 2                        # The first split is set at the threshold value (Y ≤ 0.5)
            SEED(); x1_rand = np.random.randint(1,   10001, 20000)/10000
            SEED(); x2_rand = np.random.randint(5001,10001, 20000)/10000
            SEED(); x3_rand = np.random.randint(1,   10001, 20000)/10000
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kn': x3_rand})


    elif var2 == "Kt":          # Second Split: Kt, Third Split: Kn
        x4 = ["B"] * 10000      # The second split is set along the relevant class (Kt = "B")
        df["Kt"] = x4
        df_append = create_dataset(r_S=r_S * (depth_faktor ** 2), size = 10000,
                                   xlim_min = 0, xlim_max = 1, depth = 1, type = type)
        SEED(); df_append['Kn'] = np.random.randint(1,10001, 10000) / 10000
        SEED(); df_append['Kt'] = np.random.choice(["A", "C", "D", "E"], 10000)
        df = pd.concat([df, df_append], ignore_index=True)

        if var1 == "X":                         # First Split: X, Second Split: Kt, Third Split: Kn
            df["X"] /= 2                        # The first split is set at the threshold value (X ≤ 0.5)
            SEED(); x1_rand = np.random.randint(5001,10001, 20000) / 10000
            SEED(); x2_rand = np.random.randint(1,   10001, 20000) / 10000
            SEED(); x3_rand = np.random.randint(1,   10001, 20000) / 10000
            SEED(); x4_rand = np.random.choice(["A", "B", "C", "D", "E"], 20000)
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kn': x3_rand, 'Kt': x4_rand})

        if var1 == "Y":                         # First Split: Y, Second Split: Kt, Third Split: Kn
            df["Y"] /= 2                        # The first split is set at the threshold value (Y ≤ 0.5)
            SEED(); x1_rand = np.random.randint(1,   10001, 20000) / 10000
            SEED(); x2_rand = np.random.randint(5001,10001, 20000) / 10000
            SEED(); x3_rand = np.random.randint(1,   10001, 20000) / 10000
            SEED(); x4_rand = np.random.choice(["A", "B", "C", "D", "E"], 20000)
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kn': x3_rand, 'Kt': x4_rand})


    elif var2 == "Y":   # NOTE: A new initial data set is created here to adjust the limits ...
                        # ... for the Y-Split to the gradient of the subsequent Kn-Split.
        df = create_dataset(r_S=r_S, size=1000, depth=3, xlim_min = 0, xlim_max = 0.5, type = type)
        SEED(); x3_df = np.random.randint(1, 1001, 1000) / 10000
        df["Kn"] = x3_df
        df_append = create_dataset(r_S=r_S * depth_faktor, size=9000, depth=2,
                                   xlim_min = 0, xlim_max = 0.5, type = type)
        SEED(); x3_append = np.random.randint(1001, 10001, 9000) / 10000
        df_append["Kn"] = x3_append
        df = pd.concat([df, df_append], ignore_index=True)
        X, Y = df["X"], df["Y"]       # Interchange X- and Y-coordinates
        df["X"], df["Y"] = X, Y

        # Data set for the second split:
        # Second Split: Y, Third Split: Kn
        # The second split is set at the threshold value (Y ≤ 0.5)
        df_append = create_dataset(r_S=r_S * (depth_faktor ** 2), size = 10000,
                                   xlim_min = 0.5, xlim_max = 1, depth = 1, type = type)
        X, Y = df_append["Y"], df_append["X"]
        df_append["X"], df_append["Y"] = X, Y
        SEED(); df_append["Kn"] = np.random.randint(1,   10001, 10000) / 10000
        df = pd.concat([df, df_append], ignore_index=True)

        if var1 == "X":                         # First Split: X, Second Split: Y, Third Split: Kn
            df['X'] /= 2                        # The first split is set at the threshold value (X ≤ 0.5)
            SEED(); x1_rand = np.random.randint(5001,10001, 20000) / 10000
            SEED(); x2_rand = np.random.randint(1,   10001, 20000) / 10000
            SEED(); x3_rand = np.random.randint(1,   10001, 20000) / 10000
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kn': x3_rand})

        elif var1 == "Kt":                      # First Split: Kt, Second Split: Y, Third Split: Kn
            df["Kt"] = ["C"] * 20000            # The first split is set along the relevant class (Kt = "C")
            SEED(); x1_rand = np.random.randint(1,   10001, 20000) / 10000
            SEED(); x2_rand = np.random.randint(1,   10001, 20000) / 10000
            SEED(); x3_rand = np.random.randint(1,   10001, 20000) / 10000
            SEED(); x4_rand = np.random.choice(["A", "B", "D", "E"], 20000)
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kn': x3_rand, 'Kt': x4_rand})


    df = pd.concat([df, df_append], ignore_index=True)  # The partial data sets are merged and returned
    if printit: print_dataset(df)
    return df

#create_var1_var2_Kn(r_S = 1, var1 = "Kt", var2 = "X",  printit = True, type = "lin")
#create_var1_var2_Kn(r_S = 1, var1 = "Y",  var2 = "X",  printit = True, type = "lin")
#create_var1_var2_Kn(r_S = 1, var1 = "X",  var2 = "Kt", printit = True, type = "lin")
#create_var1_var2_Kn(r_S = 1, var1 = "Y",  var2 = "Kt", printit = True, type = "lin")
#create_var1_var2_Kn(r_S = 1, var1 = "X",  var2 = "Y",  printit = True, type = "lin")
#create_var1_var2_Kn(r_S = 1, var1 = "Kt", var2 = "Y",  printit = True, type = "lin")

def create_var1_var2_Kt(r_S, var1, var2, printit = False, type ="lin"):
    # Create the highly functional relationship after three splits (df) ...
    # ... and a weakened relationship after two splits (df_append) and combine both.
    # The third split is implemented along the relevant class Kt = "A":
    df = create_dataset(r_S=r_S, size = 1000, depth = 3, xlim_min = 0, type = type)
    x3 = ["A"] * 1000
    df['Kt'] = x3
    df_append = create_dataset(r_S=r_S * depth_faktor, size = 9000, depth = 2, type = type)
    SEED(); x3_append = np.random.choice(["B", "C", "D", "E"], 9000)
    df_append['Kt'] = x3_append
    df = pd.concat([df, df_append], ignore_index=True)


    if var2 == "X": # NOTE: A new initial data set is created here to adjust the limits ...
                    # ... for the X-Split to the gradient of the subsequent Kt-Split.
        df = create_dataset(r_S=r_S, size=1000, xlim_min = 0, xlim_max = 0.5, depth=3, type = type)
        x3 = ["A"] * 1000
        df['Kt'] = x3
        df_append = create_dataset(r_S=r_S * depth_faktor, size=9000, xlim_max = 0.5, depth = 2, type = type)
        SEED(); x3_append = np.random.choice(["B", "C", "D", "E"], 9000)
        df_append['Kt'] = x3_append
        df = pd.concat([df, df_append], ignore_index=True)

        # Data set for the second split:
        # Second Split: X, Third Split: Kt
        # The second split is set at the threshold value (X ≤ 0.5)
        df_append = create_dataset(r_S=r_S * (depth_faktor ** 2), size=10000, xlim_min = 0.5,
                                   xlim_max = 1, depth=1, type = type)
        SEED(); df_append['Kt']  = np.random.choice(["A", "B", "C", "D", "E"], 10000)
        df = pd.concat([df, df_append], ignore_index=True)

        if var1 == "Kn":                        # First Split: Kn, Second Split: X, Third Split: Kt
                                                # The first split is set at the threshold value (Kn ≤ 0.5)
            SEED(); df["Kn"] = np.random.randint(1,    5001,20000) / 10000
            SEED(); x1_rand= np.random.randint(1,   10001,20000) / 10000
            SEED(); x2_rand= np.random.randint(1,   10001,20000) / 10000
            SEED(); x3_rand= np.random.choice(["A", "B", "C", "D", "E"], 20000)
            SEED(); x4_rand= np.random.randint(5001,10001,20000) / 10000
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kt': x3_rand, 'Kn': x4_rand})

        elif var1 == "Y":                       # First Split: Y, Second Split: X, Third Split: Kt
            df['Y'] /= 2                        # The first split is set at the threshold value (Y ≤ 0.5)
            SEED(); x1_rand  = np.random.randint(1,   10001,20000) / 10000
            SEED(); x2_rand  = np.random.randint(5001,10001,20000) / 10000
            SEED(); x3_rand  = np.random.choice(["A", "B", "C", "D", "E"], 20000)
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kt': x3_rand})


    elif var2 == "Kn":      # Second Split: Kn, Third Split: Kt
                            # The second split is set at the threshold value (Kn ≤ 0.5)
        SEED(); df['Kn']        = np.random.randint(1,    5001, 10000) / 10000
        df_append               = create_dataset(r_S=r_S * (depth_faktor ** 2), size=10000, depth=1, type = type)
        SEED(); df_append['Kt'] = np.random.choice(["A", "B", "C", "D", "E"], 10000)
        SEED(); df_append['Kn'] = np.random.randint(5001,10001, 10000) / 10000
        df = pd.concat([df, df_append], ignore_index=True)

        if var1 == "X":                         # First Split: X, Second Split: Kn, Third Split: Kt
            df['X'] /= 2                        # The first split is set at the threshold value (X ≤ 0.5)
            SEED(); x1_rand = np.random.randint(5001,  10001, 20000) / 10000
            SEED(); x2_rand = np.random.randint(1,     10001, 20000) / 10000
            SEED(); x3_rand  = np.random.choice(["A", "B", "C", "D", "E"], 20000)
            SEED(); x4_rand = np.random.randint(1,     10001, 20000) / 10000
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kt': x3_rand, 'Kn': x4_rand})

        elif var1 == "Y":                       # First Split: Y, Second Split: Kn, Third Split: Kt
            df['Y'] /= 2                        # The first split is set at the threshold value (Y ≤ 0.5)
            SEED(); x1_rand = np.random.randint(1,    10001, 20000) / 10000
            SEED(); x2_rand = np.random.randint(5001, 10001, 20000) / 10000
            SEED(); x3_rand = np.random.choice(["A", "B", "C", "D", "E"], 20000)
            SEED(); x4_rand = np.random.randint(1,    10001, 20000) / 10000
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kt': x3_rand, 'Kn': x4_rand})


    elif var2 == "Y": # NOTE: A new initial data set is created here to adjust the limits ...
                        # ... for the Y-Split to the gradient of the subsequent Kt-Split.
        df = create_dataset(r_S=r_S, size=1000, depth=3, xlim_min=0, xlim_max = 0.5, type = type)
        x3 = ["A"] * 1000
        df['Kt'] = x3
        df_append = create_dataset(r_S=r_S * depth_faktor, size=9000, depth=2, xlim_max = 0.5, type = type)
        SEED(); x3_append = np.random.choice(["B", "C", "D", "E"], 9000)
        df_append['Kt'] = x3_append
        df = pd.concat([df, df_append], ignore_index=True)
        X, Y = df['Y'], df['X']  # Interchange X- and Y-coordinates
        df['Y'], df['X'] = Y, X

        # Data set for the second split:
        # Second Split: Y, Third Split: Kt
        # The second split is set at the threshold value (Y ≤ 0.5)
        df_append       = create_dataset(r_S=r_S * (depth_faktor ** 2), size=10000, depth=1,
                                         xlim_min=0.5, xlim_max = 1, type = type)
        SEED(); df_append['Kt'] = np.random.choice(["A", "B", "C", "D", "E"], 10000)
        df = pd.concat([df, df_append], ignore_index=True)

        if var1 == "X":                         # First Split: X, Second Split: Y, Third Split: Kt
            df['X'] /= 2                        # The first split is set at the threshold value (X ≤ 0.5)
            SEED(); x1_rand = np.random.randint(5001, 10001, 20000) / 10000
            SEED(); x2_rand = np.random.randint(1,    10001, 20000) / 10000
            SEED(); x3_rand  = np.random.choice(["A", "B", "C", "D", "E"], 20000)
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kt': x3_rand})

        elif var1 == "Kn":                      # First Split: Kn, Second Split: Y, Third Split: Kt
                                                # The first split is set at the threshold value (Kn ≤ 0.5)
            SEED(); df['Kn'] = np.random.randint(1,   5001, 20000) / 10000
            SEED(); x1_rand  = np.random.randint(1,  10001, 20000) / 10000
            SEED(); x2_rand  = np.random.randint(1,  10001, 20000) / 10000
            SEED(); x3_rand  = np.random.choice(["A", "B", "C", "D", "E"], 20000)
            SEED(); x4_rand = np.random.randint(5001,10001, 20000) / 10000
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kt': x3_rand, 'Kn': x4_rand})

    df = pd.concat([df, df_append], ignore_index=True) # The partial data sets are merged and returned
    if printit: print_dataset(df)
    return df

#create_var1_var2_Kt(1, "Kn", "X",  printit = True, type = "lin")
#create_var1_var2_Kt(1, "Y",  "X",  printit = True, type = "lin")
#create_var1_var2_Kt(1, "X",  "Kn", printit = True, type = "lin")
#create_var1_var2_Kt(1, "Y",  "Kn", printit = True, type = "lin")
#create_var1_var2_Kt(1, "X",  "Y",  printit = True, type = "lin")
#create_var1_var2_Kt(1, "Kn", "Y",  printit = True, type = "lin")

def create_var1_var2_Y(r_S, var1, var2, printit = False, type ="lin"):
    # Create the highly functional relationship after three splits (df) ...
    # ... and a weakened relationship after two splits (df_append) and combine both.
    # The third split is implemented at the threshold value Y ≤ 0.1.
    # To simplify the construction, the case with a last split in Y can be traced back ...
    # ... to the case with the last split in X by interchanging the indices
    df = create_dataset(r_S=r_S, size = 1000, xlim_min = 0, xlim_max = 0.1, depth = 3, type = type)
    X, Y = df["Y"], df["X"]                     # Interchange X- and Y-coordinates
    df["X"], df["Y"] = X, Y
    df_append = create_dataset(r_S=r_S * depth_faktor, size = 9000, xlim_min = 0.1, xlim_max = 1, depth = 2, type = type)
    X, Y = df_append["Y"], df_append["X"]       # Interchange X- and Y-coordinates
    df_append["X"], df_append["Y"] = X, Y
    df = pd.concat([df, df_append], ignore_index= True)

    if var2 == "X":     # Second Split: X, Third Split: Y
        df["X"] /= 2    # The second split is set at the threshold value (X ≤ 0.5)
        df_append = create_dataset(r_S=r_S * (depth_faktor ** 2), size = 10000, depth = 1, type = type)
        X, Y = df_append["Y"], df_append["X"]       # Interchange X- and Y-coordinates
        df_append["X"], df_append["Y"] = X/2 + 0.5, Y
        df = pd.concat([df, df_append], ignore_index=True)

        if var1 == "Kn":                        # First Split: Kn, Second Split: X, Third Split: Y
                                                # The first split is set at the threshold value (Kn ≤ 0.5)
            SEED(); df['Kn']= np.random.randint(1,     5001, 20000) / 10000
            SEED(); x1_rand = np.random.randint(1,    10001, 20000) / 10000
            SEED(); x2_rand = np.random.randint(1,    10001, 20000) / 10000
            SEED(); x3_rand = np.random.randint(5001, 10001, 20000) / 10000
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kn': x3_rand})

        elif var1 == "Kt":                      # First Split: Kt, Second Split: X, Third Split: Y
            df['Kt']= ["C"] * 20000             # The first split is set along the relevant class (Kt = "C")
            SEED(); x1_rand = np.random.randint(1,    10001, 20000) / 10000
            SEED(); x2_rand = np.random.randint(1,    10001, 20000) / 10000
            SEED(); x3_rand = np.random.choice(["A", "B", "D", "E"], 20000)
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kt': x3_rand})


    elif var2 == "Kn":      # Second Split: Kn, Third Split: Y
                            # The second split is set at the threshold value (Kn ≤ 0.5)
        SEED(); df["Kn"]       = np.random.randint(1,     5001, 10000) / 10000
        df_append      = create_dataset(r_S=r_S * (depth_faktor ** 2), size = 10000, depth = 1, type = type)
        SEED(); df_append["Kn"]= np.random.randint(5001, 10001, 10000) / 10000
        X, Y = df_append["Y"], df_append["X"]       # Interchange X- and Y-coordinates
        df_append["X"], df_append["Y"] = X, Y
        df = pd.concat([df, df_append], ignore_index=True)

        if var1 == "X":                         # First Split: X, Second Split: Kn, Third Split: Y
            df['X'] /= 2                        # The first split is set at the threshold value (X ≤ 0.5)
            SEED(); x1_rand = np.random.randint(5001, 10001, 20000) / 10000
            SEED(); x2_rand = np.random.randint(1,    10001, 20000) / 10000
            SEED(); x3_rand = np.random.randint(1,    10001, 20000) / 10000
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kn': x3_rand})

        if var1 == "Kt":                        # First Split: Kt, Second Split: Kn, Third Split: Y
            df['Kt'] = ["C"] * 20000            # The first split is set along the relevant class (Kt = "C")
            SEED(); x1_rand = np.random.randint(1,    10001, 20000) / 10000
            SEED(); x2_rand = np.random.randint(1,    10001, 20000) / 10000
            SEED(); x3_rand = np.random.randint(1,    10001, 20000) / 10000
            SEED(); x4_rand = np.random.choice(["A", "B", "D", "E"], 20000)
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kn': x3_rand, 'Kt': x4_rand})

    elif var2 == "Kt":                  # Second Split: Kt, Third Split: Y
        df["Kt"]       = ["B"] * 10000  # The second split is set along the relevant class (Kt = "B")
        df_append      = create_dataset(r_S=r_S * (depth_faktor ** 2), size = 10000, depth = 1, type = type)
        SEED(); df_append["Kt"]= np.random.choice(["A", "C", "D", "E"], 10000)
        X, Y = df_append["Y"], df_append["X"]       # Interchange X- and Y-coordinates
        df_append["X"], df_append["Y"] = X, Y
        df = pd.concat([df, df_append], ignore_index=True)

        if var1 == "X":                         # First Split: X, Second Split: Kt, Third Split: Y
            df['X'] /= 2                        # The first split is set at the threshold value (X ≤ 0.5)
            SEED(); x1_rand = np.random.randint(5001, 10001, 20000) / 10000
            SEED(); x2_rand = np.random.randint(1,    10001, 20000) / 10000
            SEED(); x3_rand = np.random.choice(["A", "B", "C", "D", "E"], 20000)
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kt': x3_rand})

        elif var1 == "Kn":                      # First Split: Kn, Second Split: Kt, Third Split: Y
                                                # The first split is set at the threshold value (Kn ≤ 0.5)
            SEED(); df['Kn']= np.random.randint(1,     5001, 20000) / 10000
            SEED(); x1_rand = np.random.randint(1,    10001, 20000) / 10000
            SEED(); x2_rand = np.random.randint(1,    10001, 20000) / 10000
            SEED(); x3_rand = np.random.choice(["A", "B", "C", "D", "E"], 20000)
            SEED(); x4_rand = np.random.randint(5001, 10001, 20000) / 10000
            df_append = pd.DataFrame({'X': x1_rand, 'Y': x2_rand, 'Kt': x3_rand, 'Kn': x4_rand})

    df = pd.concat([df, df_append], ignore_index= True) # The partial data sets are merged and returned
    if printit: print_dataset(df)
    return df


#create_var1_var2_Y(1, "Kn", "X",  printit = True, type = "lin") # NOTE: this case is excluded in the thesis.
#create_var1_var2_Y(1, "Kt", "X",  printit = True, type = "lin") # NOTE: this case is excluded in the thesis.
                                                                 # The two data sets that can be called up here only...
                                                                 # ... serve to illustrate the problem that arises.
#create_var1_var2_Y(1, "X",  "Kn", printit = True, type = "lin")
#create_var1_var2_Y(1, "Kt", "Kn", printit = True, type = "lin")
#create_var1_var2_Y(1, "X",  "Kt", printit = True, type = "lin")
#create_var1_var2_Y(1, "Kn", "Kt", printit = True, type = "lin")


#____________________________________________________________
#____________________________________________________________
# Aggregation of all possible combinations in the creation of a test data set in one shared function:

# The function takes the specifications according to Table 3.3 as input and returns the corresponding data set
def test_data(split1, split2, split3, r_S, printit = False, type ="lin", interf_var = False, seed = None):
    # Check the arguments for possible splits:
    if ((split1 not in ["O", "X", "Kn", "Kt", "Y"]) or (split2 not in ["O", "X", "Kn", "Kt", "Y"])
            or (split3 not in ["X", "Kn", "Kt", "Y"])):
        print("Wrong input")
        return
    if (split1 == split2) or (split1 == split3) or (split2 == split3):
        if not ((split1 == "O") and (split2 == "O")):
            print("Split variables must be different in pairs.")
            return

    # Check the value range for the strength and the type of the relationship
    if (r_S < -1) or (r_S > 1):
        print("Correlation value (Pearson r) must be between -1 and 1.")
        return
    if type not in ["lin", "squ", "cub", "exp", "srt", "sin", "ggk"]:
        print("Function type must be one of the following: 'lin', 'squ', 'cub', 'exp', 'srt', 'sin' or 'ggk'.")
        return

    # Acquiring the global seed
    global seed_val; seed_val = seed

    # Calling the previous functions, depending on the number of splits:
    if (split1 == "O") and (split2 == "O"):
        function_name = f"create_{split3}"
        func = globals()[function_name]
        df = func(r_S = r_S, type = type)

    elif (split1 == "O") and (split2 != "O"):
        function_name = f"create_var1_{split3}"
        func = globals()[function_name]
        df = func(r_S = r_S, var1 = split2, type = type)

    elif (split1 != "O") and (split2 != "O"):
        function_name = f"create_var1_var2_{split3}"
        func = globals()[function_name]
        df = func(r_S = r_S, var1 = split1, var2 = split2, type = type)

    else: # when split1 == "O" and split2 ≠ 0
        print("Wrong input. Split2 can't be 'O', when split1 ≠ O.")
        return

    size = len(df)

    # Convert "Kt" to a categorical variable if it appears in split1, split2, or split3
    if "Kt" in [split1, split2, split3]:
        df["Kt"] = pd.Categorical(df["Kt"], categories=["A", "B", "C", "D", "E"])


    # add disturbance variables:
    # - one categorical
    # - one continuous-equally distributed
    # - one continuous-normally distributed variable
    if interf_var:
        SEED(); df["kat"] = np.random.choice(["v", "w", "x", "y", "z"], size)
        df["kat"]         = pd.Categorical(df["kat"], categories=["v", "w", "x", "y", "z"])

        SEED(); df["kog"] = np.random.randint(1, 10001, size) / 10000

        SEED(); x_append = np.random.normal(0, 1, size)
        x_append         = (x_append / 6) + 0.5
        for i in range(len(x_append)):  # Redistribution if the values are outside [0,1]
            if (x_append[i] <= 0) or (x_append[i] >1):
                SEED(); x_append[i] =np.random.randint(1,10001)/10000
        df["kon"] = x_append

    if printit:
        print_dataset(df)
    return df

#Testaufruf
#a = test_data("Kt","Kn","X", 1, type = "lin", printit = True, interf_var = True, seed = 1)
#b = test_data("Kt","Kn","X", 1, type = "lin", printit = False, interf_var = True, seed = 2)